version: '3'
services:
  proxy:
    build: ./
    networks:
        - website1
        - website2 
    ports:
      - "80:80"
    container_name: proxy 

networks:
  website1:
    external: 
      name: website1_default
  website2:
    external: 
      name: website2_default